# working dir of scripts and main interpreter.
pwd: .

# runtime config
runtime:
  # path of user database, will be injected into scripts.
  user-db: ./data/random-users.py

job:
  path: ./jobs/example_weather.job
  # halts program on job scripts syntax errors.
  halt-onerror: true


scripts: 
  # halts robot on runpy errors or timeouts.
  halt-onerror: false #脚本出错是否停止
  dirs: 
    - ./scripts/
